#include "HL2StaticPropMeshBuilder.h"
#include "HL2StudioTypes.h"
#include "HL2BSPImporter.h"
#include "HL2BSPImporterSettings.h"
#include "HL2MaterialBuilder.h"

#include "AssetRegistry/AssetRegistryModule.h"
#include "Engine/StaticMesh.h"
#include "Materials/Material.h"
#include "Materials/MaterialInterface.h"
#include "MeshDescription.h"
#include "PhysicsEngine/BodySetup.h"
#include "StaticMeshAttributes.h"
#include "StaticMeshOperations.h"
#include "UObject/Package.h"

namespace HL2Studio
{
    namespace
    {
        // Same Source-to-Unreal coordinate transform used by the BSP importer
        // (HL2BSPImporterFactory.cpp::TransformPos). Re-implemented here to
        // avoid leaking that file's anonymous-namespace helpers across TUs.
        FORCEINLINE FVector TransformPos(const FVector& In, const UHL2BSPImporterSettings* S)
        {
            FVector P = In;
            if (S && S->bFlipYZ) { P = FVector(In.X, In.Z, In.Y); }
            P.Y *= -1.f;
            const float Scale = S ? S->WorldScale : 1.f;
            return P * Scale;
        }

        FORCEINLINE FVector TransformDir(const FVector& In, const UHL2BSPImporterSettings* S)
        {
            FVector P = In;
            if (S && S->bFlipYZ) { P = FVector(In.X, In.Z, In.Y); }
            P.Y *= -1.f;
            // Direction vectors are normalised post-transform; uniform scale doesn't matter.
            return P.GetSafeNormal();
        }

        // The Source→Unreal transform's net handedness flip means triangle
        // winding has to be reversed for faces to render front-side; this
        // matches the BSP path's ShouldReverseWinding behaviour.
        FORCEINLINE bool ShouldReverseWinding(const UHL2BSPImporterSettings*) { return true; }

        // Resolve a mesh's material to a UE MaterialInterface by trying every
        // candidate path the MDL provided (most-likely first per Source's
        // cdtex search order). Falls back to the engine default surface
        // material when nothing resolves; the slot name is kept as the first
        // candidate so a project can still author a one-off override against
        // it via the JSON map without re-running the synthesizer.
        UMaterialInterface* ResolveMaterial(
            const TArray<FString>& Candidates,
            HL2Mat::FBuilder& MatBuilder,
            FName& OutSlot)
        {
            for (const FString& C : Candidates)
            {
                if (UMaterialInterface* M = MatBuilder.GetOrCreateMaterial(C))
                {
                    OutSlot = FName(*C);
                    return M;
                }
            }
            // Default-material path: use the first candidate as the slot name
            // so the slot is identifiable in the Material Editor.
            OutSlot = Candidates.Num() > 0 ? FName(*Candidates[0]) : FName(TEXT("Default"));
            return UMaterial::GetDefaultMaterial(MD_Surface);
        }
    } // namespace

    UStaticMesh* BuildStaticMesh(
        const FStudioFile& Studio,
        const UHL2BSPImporterSettings* Sets,
        HL2Mat::FBuilder& MatBuilder,
        UObject* Outer,
        FName Name,
        EObjectFlags Flags,
        int32 SkinIndex,
        int32 BodyMask)
    {
        if (!Outer)
        {
            UE_LOG(LogHL2BSPImporter, Error, TEXT("StaticPropMeshBuilder: null Outer"));
            return nullptr;
        }
        if (Studio.Vertices.Num() == 0)
        {
            UE_LOG(LogHL2BSPImporter, Warning,
                TEXT("StaticPropMeshBuilder: no vertices in '%s'"), *Studio.MdlPath);
            return nullptr;
        }

        FMeshDescription MD;
        FStaticMeshAttributes Attrs(MD);
        Attrs.Register();

        TVertexAttributesRef<FVector3f>          VertexPositions  = Attrs.GetVertexPositions();
        TVertexInstanceAttributesRef<FVector3f>  InstanceNormals  = Attrs.GetVertexInstanceNormals();
        TVertexInstanceAttributesRef<FVector3f>  InstanceTangents = Attrs.GetVertexInstanceTangents();
        TVertexInstanceAttributesRef<float>      InstanceBinormalSigns = Attrs.GetVertexInstanceBinormalSigns();
        TVertexInstanceAttributesRef<FVector4f>  InstanceColors   = Attrs.GetVertexInstanceColors();
        TVertexInstanceAttributesRef<FVector2f>  InstanceUVs      = Attrs.GetVertexInstanceUVs();
        InstanceUVs.SetNumChannels(2); // 0 = base UV, 1 = lightmap UVs (auto-generated by Build())

        TPolygonGroupAttributesRef<FName> PolyGroupSlots = Attrs.GetPolygonGroupMaterialSlotNames();

        const bool bReverse = ShouldReverseWinding(Sets);

        // Global-vertex -> FVertexID map. Static props don't typically share
        // vertices across meshes, but doing it this way Just Works either way.
        TMap<int32, FVertexID> GlobalToVertex;
        GlobalToVertex.Reserve(Studio.Vertices.Num());

        // Per-(global vertex, polygon group) -> FVertexInstanceID. A vertex
        // shared between two materials needs two instances (different normals
        // / UVs are allowed; the position is shared).
        struct FInstKey
        {
            int32          GlobalVert;
            FPolygonGroupID PG;
            bool operator==(const FInstKey& O) const { return GlobalVert == O.GlobalVert && PG == O.PG; }
        };
        struct FInstKeyHash
        {
            uint32 operator()(const FInstKey& K) const { return HashCombine(::GetTypeHash(K.GlobalVert), ::GetTypeHash(K.PG.GetValue())); }
        };
        TMap<int32, FVertexInstanceID> InstanceCache; // re-allocated per polygon group below

        TArray<FName> SlotOrder;
        TMap<int32, UMaterialInterface*> MaterialByPgIndex;
        int32 PgIndex = 0;
        int64 EmittedTriangles = 0;

        // Skin remap: mesh.MaterialIndex is a ref-slot; the skin table maps
        // it to a real texture index. Identity when the model has no skin
        // table, the requested SkinIndex is out of range, or the ref-slot is
        // out of range for this family.
        const FStudioSkinTable& SkinTbl = Studio.Skin;
        const bool bHasSkinTable =
            SkinTbl.SkinFamilies.Num() > 0
            && SkinTbl.NumSkinRef > 0
            && SkinTbl.SkinFamilies.IsValidIndex(SkinIndex);
        const TArray<int32>* SkinRow = bHasSkinTable ? &SkinTbl.SkinFamilies[SkinIndex] : nullptr;

        auto ApplySkin = [SkinRow, &Studio](int32 RefSlot) -> int32
        {
            if (SkinRow && SkinRow->IsValidIndex(RefSlot))
            {
                const int32 TexIdx = (*SkinRow)[RefSlot];
                if (Studio.MaterialCandidates.IsValidIndex(TexIdx)) { return TexIdx; }
            }
            return RefSlot;
        };

        // Bodygroup decode: Source's `body` keyvalue is a packed integer mask. The
        // selected model index for bodypart `bp` is `(mask / base[bp]) % nummodels[bp]`,
        // where `base[0] = 1` and `base[bp+1] = base[bp] * nummodels[bp]`. BodyMask 0
        // (the prop_static default and the prop_dynamic default) selects Models[0] of
        // every bodypart, matching the prior Phase 12a behaviour exactly.
        int32 BodypartBase = 1;
        for (const FStudioBodyPart& Bp : Studio.BodyParts)
        {
            if (Bp.Models.Num() == 0) { continue; }
            int32 ModelIdx = 0;
            if (BodyMask != 0)
            {
                ModelIdx = (BodyMask / BodypartBase) % Bp.Models.Num();
                if (!Bp.Models.IsValidIndex(ModelIdx)) { ModelIdx = 0; }
            }
            BodypartBase *= Bp.Models.Num();
            const FStudioModel& Model = Bp.Models[ModelIdx];
            {
                for (const FStudioMesh& Mesh : Model.Meshes)
                {
                    if (Mesh.TriangleIndices.Num() < 3) { continue; }
                    const int32 EffMatIdx = ApplySkin(Mesh.MaterialIndex);
                    if (!Studio.MaterialCandidates.IsValidIndex(EffMatIdx)) { continue; }

                    FName SlotName;
                    UMaterialInterface* Mat = ResolveMaterial(
                        Studio.MaterialCandidates[EffMatIdx], MatBuilder, SlotName);

                    // Polygon group per (material slot). A model with two
                    // meshes that use the same material collapses into one PG.
                    FPolygonGroupID PG;
                    {
                        const int32 ExistingIdx = SlotOrder.IndexOfByKey(SlotName);
                        if (ExistingIdx == INDEX_NONE)
                        {
                            PG = MD.CreatePolygonGroup();
                            PolyGroupSlots[PG] = SlotName;
                            SlotOrder.Add(SlotName);
                            MaterialByPgIndex.Add(PG.GetValue(), Mat);
                            ++PgIndex;
                        }
                        else
                        {
                            // Find the existing PG by walking allocated groups
                            // and matching slot name; simpler than maintaining
                            // a parallel map.
                            PG = FPolygonGroupID(INDEX_NONE);
                            for (FPolygonGroupID Iter : MD.PolygonGroups().GetElementIDs())
                            {
                                if (PolyGroupSlots[Iter] == SlotName) { PG = Iter; break; }
                            }
                            check(PG != FPolygonGroupID(INDEX_NONE));
                        }
                    }

                    InstanceCache.Reset();

                    auto GetOrCreateVertex = [&](int32 GlobalVertIdx) -> FVertexID
                    {
                        if (FVertexID* V = GlobalToVertex.Find(GlobalVertIdx)) { return *V; }
                        const FStudioVertex& Sv = Studio.Vertices[GlobalVertIdx];
                        const FVertexID NewV = MD.CreateVertex();
                        VertexPositions[NewV] = (FVector3f)TransformPos(Sv.Position, Sets);
                        GlobalToVertex.Add(GlobalVertIdx, NewV);
                        return NewV;
                    };

                    auto GetOrCreateInstance = [&](int32 GlobalVertIdx) -> FVertexInstanceID
                    {
                        if (FVertexInstanceID* I = InstanceCache.Find(GlobalVertIdx)) { return *I; }
                        const FVertexID V = GetOrCreateVertex(GlobalVertIdx);
                        const FVertexInstanceID VI = MD.CreateVertexInstance(V);
                        const FStudioVertex& Sv = Studio.Vertices[GlobalVertIdx];
                        InstanceUVs.Set(VI, 0, FVector2f((float)Sv.UV.X, (float)Sv.UV.Y));
                        InstanceUVs.Set(VI, 1, FVector2f((float)Sv.UV.X, (float)Sv.UV.Y));
                        InstanceNormals[VI]  = FVector3f(TransformDir(Sv.Normal, Sets));
                        InstanceTangents[VI] = FVector3f(TransformDir(FVector(Sv.Tangent.X, Sv.Tangent.Y, Sv.Tangent.Z), Sets));
                        InstanceBinormalSigns[VI] = (Sv.Tangent.W < 0.f) ? -1.f : 1.f;
                        InstanceColors[VI]   = FVector4f(1.f, 1.f, 1.f, 1.f);
                        InstanceCache.Add(GlobalVertIdx, VI);
                        return VI;
                    };

                    const int32 NumTris = Mesh.TriangleIndices.Num() / 3;
                    for (int32 t = 0; t < NumTris; ++t)
                    {
                        const uint32 LocalA = Mesh.TriangleIndices[t * 3 + 0];
                        const uint32 LocalB = Mesh.TriangleIndices[t * 3 + 1];
                        const uint32 LocalC = Mesh.TriangleIndices[t * 3 + 2];

                        const int32 GA = Model.VertexBase + Mesh.VertexOffset + (int32)LocalA;
                        const int32 GB = Model.VertexBase + Mesh.VertexOffset + (int32)LocalB;
                        const int32 GC = Model.VertexBase + Mesh.VertexOffset + (int32)LocalC;
                        if (!Studio.Vertices.IsValidIndex(GA)
                         || !Studio.Vertices.IsValidIndex(GB)
                         || !Studio.Vertices.IsValidIndex(GC)) { continue; }

                        // Degenerate filter: identical indices.
                        if (GA == GB || GB == GC || GA == GC) { continue; }

                        FVertexInstanceID I0 = GetOrCreateInstance(GA);
                        FVertexInstanceID I1 = GetOrCreateInstance(GB);
                        FVertexInstanceID I2 = GetOrCreateInstance(GC);
                        if (bReverse) { Swap(I1, I2); }

                        TArray<FVertexInstanceID, TFixedAllocator<3>> Tri;
                        Tri.Add(I0); Tri.Add(I1); Tri.Add(I2);
                        MD.CreatePolygon(PG, Tri);
                        ++EmittedTriangles;
                    }
                }
            }
        }

        if (EmittedTriangles == 0)
        {
            UE_LOG(LogHL2BSPImporter, Warning,
                TEXT("StaticPropMeshBuilder: zero triangles produced for '%s'"), *Studio.MdlPath);
            return nullptr;
        }

        // ---- Build the UStaticMesh ----
        UStaticMesh* M = NewObject<UStaticMesh>(Outer, UStaticMesh::StaticClass(), Name, Flags);
        if (!M)
        {
            UE_LOG(LogHL2BSPImporter, Error,
                TEXT("StaticPropMeshBuilder: NewObject<UStaticMesh> failed (outer=%s, name=%s)"),
                *GetNameSafe(Outer), *Name.ToString());
            return nullptr;
        }
        M->NaniteSettings.bEnabled = Sets ? Sets->bBuildNanite : true;

        FStaticMeshSourceModel& SM = M->AddSourceModel();
        SM.BuildSettings.bRecomputeNormals    = false;
        SM.BuildSettings.bRecomputeTangents   = false;
        SM.BuildSettings.bRemoveDegenerates   = true;
        SM.BuildSettings.bUseMikkTSpace       = true;
        SM.BuildSettings.bGenerateLightmapUVs = true;
        SM.BuildSettings.SrcLightmapIndex     = 1;
        SM.BuildSettings.DstLightmapIndex     = 1;
        SM.BuildSettings.MinLightmapResolution = 64;

        // Source props ship with hand-authored normals/tangents on the VVD;
        // recompute via MikkTSpace so the runtime baking matches BSP world
        // geometry (and to produce tangents for meshes whose VVD lacked them).
        FStaticMeshOperations::ComputeTangentsAndNormals(
            MD,
            EComputeNTBsFlags::Normals
            | EComputeNTBsFlags::Tangents
            | EComputeNTBsFlags::WeightedNTBs
            | EComputeNTBsFlags::BlendOverlappingNormals
            | EComputeNTBsFlags::UseMikkTSpace);

        if (FMeshDescription* DestMD = M->CreateMeshDescription(0))
        {
            *DestMD = MoveTemp(MD);
            M->CommitMeshDescription(0);
        }
        else
        {
            UE_LOG(LogHL2BSPImporter, Error,
                TEXT("StaticPropMeshBuilder: UStaticMesh::CreateMeshDescription returned null"));
            return nullptr;
        }

        M->SetLightMapCoordinateIndex(1);
        M->SetLightMapResolution(64);

        // Material slots — order matches SlotOrder (= polygon-group creation order).
        TArray<FStaticMaterial> StaticMats;
        StaticMats.Reserve(SlotOrder.Num());
        for (const FName& Slot : SlotOrder)
        {
            UMaterialInterface* Mat = nullptr;
            for (const auto& Pair : MaterialByPgIndex)
            {
                if (FName(*PolyGroupSlots[FPolygonGroupID(Pair.Key)].ToString()) == Slot)
                {
                    Mat = Pair.Value;
                    break;
                }
            }
            if (!Mat) { Mat = UMaterial::GetDefaultMaterial(MD_Surface); }
            StaticMats.Add(FStaticMaterial(Mat, Slot, Slot));
        }
        M->SetStaticMaterials(StaticMats);

        M->Build(false);
        M->PostEditChange();

        if (Sets && Sets->bImportCollision && !M->GetBodySetup())
        {
            M->CreateBodySetup();
            if (UBodySetup* BS = M->GetBodySetup())
            {
                BS->CollisionTraceFlag = CTF_UseComplexAsSimple;
            }
        }

        FAssetRegistryModule::AssetCreated(M);
        if (UPackage* Pkg = M->GetOutermost()) { Pkg->MarkPackageDirty(); }

        UE_LOG(LogHL2BSPImporter, Log,
            TEXT("Static prop mesh built: %s (%lld tris, %d slots, skin=%d, body=%d) from %s"),
            *M->GetPathName(), (long long)EmittedTriangles, SlotOrder.Num(), SkinIndex, BodyMask, *Studio.MdlPath);
        return M;
    }
}
